allowBuilds:
  esbuild: true
gitChecks: false
overrides:
  entities: ^7.0.1
  parse5: npm:fake-parse5
  parse5-htmlparser2-tree-adapter: npm:fake-parse5
update:
  # FIXME: remove this on cheerio next release which should depends on domhandler 6.x and htmlparser2 12.x -> entities 8.x
  ignoreDeps:
    - domhandler
    - entities
