name: Build and Publish

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          runtime: node@lts
          cache: true

      - name: Lint
        run: pnpm run lint
      - name: Check format
        run: pnpm run fmt:check
      - name: Build library
        run: pnpm run build

      - name: Upload built library
        uses: actions/upload-artifact@v7
        with:
          name: thu-learn-lib
          path: lib/

  publish-to-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          install: false

      - name: Download build result
        uses: actions/download-artifact@v8
        with:
          name: thu-learn-lib
          path: lib/
      - name: Publish to NPM
        run: pnpm publish --provenance
